// Importing the first script
const { scrapeData } = require("./scrape");

// Importing the second script
const  scrapeAndExportData  = require("./scrapeEachInscriptionId");

// main.js

const fs = require("fs");

function checkFileExists(filePath) {
  try {
    fs.accessSync(filePath, fs.constants.F_OK);
    return true;
  } catch (error) {
    return false;
  }
}

// Call the first script
async function runFirstScript() {
  try {
    console.log("Running the first script...");
    await scrapeData();
    console.log("First script completed successfully.");
  } catch (error) {
    console.error("Error running the first script:", error);
  }
}

// Call the second script
async function runSecondScript() {
  try {
    // Wait for the JSON file generated by the first script
    console.log("Waiting for scraped_data.json to be generated...");
    await waitForFile("scraped_data.json");

    // Adding a delay of 5 seconds
    console.log("Delaying execution of the second script...");
    await delay(5000);

    // Execute the second script
    console.log("Running the second script...");
    await scrapeAndExportData();
    console.log("Second script completed successfully.");
  } catch (error) {
    console.error("Error running the second script:", error);
  }
}

// Function to wait for the JSON file to be generated
async function waitForFile(filePath) {
  while (!checkFileExists(filePath)) {
    await new Promise(resolve => setTimeout(resolve, 1000)); // Check every second
  }
}

// Function to add delay
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// Call the scripts sequentially
async function main() {
  await runFirstScript();
  await runSecondScript();
}

// Start the execution
main();
